spring.application.name=Dimade_Back
spring.data.mongodb.uri=mongodb+srv://pablo:pabloclave@dimade.pruzrxm.mongodb.net/?retryWrites=true&w=majority
#spring.data.mongodb.uri=mongodb://localhost:27017/dimade_db
frontend.url=https://proyecto-dimade.vercel.app
#frontend.url=http://localhost:5173
spring.data.mongodb.database=dimade_db
server.port=8080
spring.security.user.name=admin
spring.security.user.password=admin123
jwt.secret=dimade-super-secreta-12345678901234567890123456789012
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=codexiachile@gmail.com
spring.mail.password=wpsg kqpz yzvc ndkv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true





